### ISSUE TITLE
Social auth (Google)

### ISSUE THREAD

**Issue by kafkas** [AvenCloud/coronamap#15]
Firebase's SDK exposes an easy way to initiate external OAuth, e.g.

Facebook
https://firebase.google.com/docs/auth/web/facebook-login

Google
https://firebase.google.com/docs/auth/web/google-signin

@kafkas has gone ahead and approved Google as a sign-on provider in the Firebase app, with Facebook to follow (since it has more overhead to enable, namely creating an account/app with Facebook for Developers to get application ID and client secrets).

Given the Firebase SDK pretty much handles the OAuth redirection for us, the main things this ticket will cover include:
1. Making a button that meets Google's OAuth Button standards (https://developers.google.com/identity/branding-guidelines)
2. Displaying the button on the login screen
3. Ensure that an _existing_ user who decides to OAuth (with the same email) will be matched to the same Firebase account
4. Confirm behavior when we reach the 10k limit, e.g. will Firebase automatically tick over into their Blaze plan ($0.01 per verification) or will it hand us back a reached-limit response

**Comment by kwak123** [comment]
Email linking is _not_ provided by Firebase already. It will need to be accounted for, thankfully we do get a known errorcode.

https://firebase.google.com/docs/reference/js/firebase.auth.AuthError

**Comment by kwak123** [comment]
I checked again, it appears that error may show up if you try to sign up with another email using the _EMAIL_ authentication. Firebase seems smart enough to connect the dots itself.

**Comment by kafkas** [comment]
Nailed by @kwak123
